### ISSUE TITLE
Public readiness checklist

### ISSUE THREAD

**Issue by ctreatma** [equinix/equinix-sdk-go#5]
As of now, this repo is set to private/internal while we fill in some gaps to make it ready for other teams & for external customers.  Once this is ready for public consumption, we will delete the repo and recreate it to ensure that any unnecessary releases/tags/etc. are cleaned up.

Before this goes public, we need to:

- [x] Fill in the `README` with customer-facing information
- [x] Add a `CONTRIBUTING` document that includes contribution guidelines
- [x] Add a `DEVELOPMENT` document that includes:  how to get set up for local development, how to onboard a new service, how to update an existing service, how to cut a release
- [x] Update `examples` to use this SDK instead of metal-go to demonstrate that this is a drop-in replacement
- [x] Enable branch protection on `main`

Steps for going public:
- [x] Cut a release that _only_ includes the module name / package structure change (is otherwise identical to the last `metal-go` release
- [x] Transfer remaining issues from `equinix-labs/metal-go` to this repo
- [x] Deprecate `equinix-labs/metal-go` and include a link to this repo
- [x] Update or replace `metal-go` Labs page with a page for this SDK

**Comment by ctreatma** [comment]
This repo is now public; due to the way GitHub permissions are set up for this org, I couldn't delete this repo anyway, so I just flipped it public as-is.

`v0.30.0` has been released, with equivalent functionality to `equinix-labs/metal-go@v0.29.0`.
